version: '3.8'

services:
  # Hospital Analytics Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hospital-admin-backend
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGO_URI=mongodb+srv://vqh04092004:admin@cluster0.nnhndae.mongodb.net/hospital_analytics?retryWrites=true&w=majority&ssl=true&authSource=admin
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "3003:3003"
    networks:
      - hospital-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Hospital Analytics Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hospital-admin-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3003
      - NEXT_PUBLIC_APP_NAME=Hospital Analytics Admin Console
      - NEXT_PUBLIC_HOSPITAL_DB_NAME=hospital_analytics
      - NEXT_PUBLIC_HOSPITAL_DB_TYPE=MongoDB Atlas
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - hospital-network
    restart: unless-stopped

networks:
  hospital-network:
    driver: bridge 